// Code generated by "stringer -type=osMatchQType,badSwType"; DO NOT EDIT

package P0f

import "fmt"

const _osMatchQType_name = "NormalFuzzyGenericBoth"

var _osMatchQType_index = [...]uint8{0, 6, 11, 18, 22}

func (i osMatchQType) String() string {
	if i < 0 || i >= osMatchQType(len(_osMatchQType_index)-1) {
		return fmt.Sprintf("osMatchQType(%d)", i)
	}
	return _osMatchQType_name[_osMatchQType_index[i]:_osMatchQType_index[i+1]]
}

const _badSwType_name = "NulOsMismatchMismatch"

var _badSwType_index = [...]uint8{0, 3, 13, 21}

func (i badSwType) String() string {
	if i < 0 || i >= badSwType(len(_badSwType_index)-1) {
		return fmt.Sprintf("badSwType(%d)", i)
	}
	return _badSwType_name[_badSwType_index[i]:_badSwType_index[i+1]]
}
